# Generated by Django 2.2.4 on 2019-09-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_license_image',
            field=models.URLField(default=None),
        ),
    ]
